name: Synchronize malicious packages

on:
  workflow_dispatch: {} # allows manual trigger
  schedule:
  - cron: '0 8 * * 1-5' # every weekday at 8 UTC


permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  synchronize-malicious-packages:
    name: 'Synchronize malicious packages'
    runs-on: ubuntu-latest
    environment: Main

    steps:
      # <TESTING> Only for debugging, remove after testing
      - name: Debug OIDC Claims
        uses: github/actions-oidc-debugger@main
        with:
          audience: "octo-debugger"
      # </TESTING>

      - uses: DataDog/dd-octo-sts-action@08f2144903ced3254a3dafec2592563409ba2aa0 # v1.0.1
        id: octo-sts
        with:
          scope: DataDog/malicious-software-packages-dataset  # target repository
          policy: self.open_pr # trust policy in target repo

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-3
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          role-session-name: github-actions

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/sync-malicious-packages/requirements.txt
          pip install -r scripts/generate_manifest/requirements.txt

      - name: Synchronize malicious packages
        run: |
          for ecosystem in pypi npm; do
            python scripts/sync-malicious-packages/sync-malicious-packages.py --since $(date -d "2 month ago" +%Y-%m-%d) --destination $(pwd)/samples/$ecosystem --s3-bucket ${{ secrets.S3_BUCKET_NAME }} --dynamodb-table ${{ secrets.DYNAMODB_TABLE_NAME }} --ecosystem $ecosystem;
            python scripts/generate_manifest/generate_manifest.py --output-file $(pwd)/samples/$ecosystem/manifest.json $(pwd)/samples/$ecosystem
          done
          python scripts/update-count.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            samples/
            README.md
          commit-message: "Auto-synchronize malicious packages"
          delete-branch: true
          title: "[Bot] Auto-synchronize malicious packages"
          labels: sync
          branch-suffix: timestamp
          token: ${{ steps.octo-sts.outputs.token }}
          reviewers: |
            christophetd
            sobregosodd
            ikretz
