name: Synchronize malicious packages

on:
  workflow_dispatch: {}

  
permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  synchronize-malicious-packages:
    name: 'Synchronize malicious packages'
    runs-on: ubuntu-latest
    environment: Main

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-3
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          role-session-name: github-actions

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/sync-malicious-packages/requirements.txt
          aws --version
          which aws

      - name: Synchronize malicious packages
        run: |
          python scripts/sync-malicious-packages/sync-malicious-packages.py --since $(date -d "2 month ago" +%Y-%m-%d) --destination ./samples/pypi --s3-bucket ${{ secrets.S3_BUCKET_NAME }} --dynamodb-table ${{ secrets.DYNAMODB_TABLE_NAME }} --ecosystem pypi
          python scripts/update-count.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            samples/
            README.md
          commit-message: "Auto-synchronize malicious packages"
          delete-branch: true
          title: "[Bot] Auto-synchronize malicious packages"
          labels: sync
          branch-suffix: timestamp